[kafkaTopology]
producerVersion = "${KAFKA_PAW_EGENVURDERING_PRODUCER_VERSION}"
applicationId = "paw-arbeidssoekerregisteret-egenvurdering-api"
egenvurderingTopic = "paw-arbeidssoker-egenvurdering-beta-v1"