[producerConfig]
producerVersion = "${KAFKA_PAW_EGENVURDERING_PRODUCER_VERSION}"
applicationIdPrefix = "paw-arbeidssoekerregisteret-api-egenvurdering"
egenvurderingTopic = "${KAFKA_PAW_EGENVURDERING_TOPIC}"
