[[authProviders]]
name = "tokenx"
audiences = ["${TOKEN_X_CLIENT_ID}"]
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"
    [authProviders.requiredClaims]
    claims = [
        "acr=Level3",
        "acr=Level4",
        "acr=idporten-loa-substantial", # == Level3
        "acr=idporten-loa-high" # == Level4
    ]
    combineWithOr = true
