[kafkaTopology]
producerVersion = "${KAFKA_PAW_EGENVURDERING_PRODUCER_VERSION}"
applicationId = "paw-arbeidssoekerregisteret-egenvurdering-api"
periodeStreamIdSuffix = "${KAFKA_ARBEIDSSOKERPERIODER_STREAM_ID_SUFFIX}"
profileringStreamIdSuffix = "${KAFKA_PAW_PROFILERING_STREAM_ID_SUFFIX}"
egenvurderingStreamIdSuffix = "${KAFKA_PAW_EGENVURDERING_STREAM_ID_SUFFIX}"
periodeTopic = "paw.arbeidssokerperioder-v1"
profileringTopic = "paw.arbeidssoker-profilering-v1"
egenvurderingTopic = "paw.arbeidssoker-profilering-egenvurdering-v1"
stateStoreName = "egenvurderingStateStore"
profileringStateStoreName = "profileringStateStore"