[kafkaTopology]
producerVersion = "paw-egenvurdering-producer-v1"
applicationIdPrefix = "paw-arbeidssoekerregisteret-api-egenvurdering"
egenvurderingTopic = "arbeidssoker-egenvurdering-v1"

[oppslagApiConfig]
url = "MOCK"
scope = "api://<cluster>.<namespace>.<outbound-app-name>/.default"

[texasClientConfig]
endpoint = "http://localhost:8080/texas-dummy"
target = "http://paw-arbeidssoekerregisteret-api-oppslag"
identityProvider = "tokenx"