# Local test fixture. Do not use this key in Nais.
PAW_SIGNING_PRIVATE_KEY_PKCS8_BASE64=MHcCAQEEIK3aVD4InknFUmQKpwDkPYlhEQQ+H55/wvPVcDvTv/HtoAoGCCqGSM49AwEHoUQDQgAEsYDO4smkTdYyLW6bPh+w6WDElB9zHHJEYq1bZdFAcVNCAoYNw/l1wv/6xBT4EZu3xy5ACyKDF2W26ePmdQMNfA==
PAW_SIGNING_KEY_ID=local-paw-egenvurdering-api-ecdsa-v1
