periodeTopic="arbeidssokerperioder"
opplysningerTopic="opplysninger-om-arbeidssoeker"
profileringTopic="arbeidssoker-profilering"
bekreftelseTopic="arbeidssoker-bekreftelse"
paavnegneavTopic="arbeidssoker-bekreftelse-paavegneav"