/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package no.nav.paw.oppslagapi.model.v3

import com.fasterxml.jackson.annotation.JsonProperty
import java.net.URI
import java.time.Instant
import java.util.*

data class ProblemDetails(

    @get:JsonProperty("id")
    val id: UUID,

    @get:JsonProperty("type")
    val type: URI,

    @get:JsonProperty("status")
    val status: Int,

    @get:JsonProperty("title")
    val title: String,

    @get:JsonProperty("detail")
    val detail: String,

    @get:JsonProperty("instance")
    val instance: String,

    @get:JsonProperty("timestamp")
    val timestamp: Instant
)