apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-api-mine-stillinger
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  ingresses:
    - https://mine-stillinger-arbeidssoekerregisteret.nav.no
  port: 8080
  env:
    - name: KAFKA_KEYS_SCOPE
      value: "api://prod-gcp.paw.paw-kafka-key-generator/.default"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_TEMA
      value: "OPP"
    - name: LEDIGE_STILLINGER_BASE_URL
      value: "http://paw-arbeidssoekerregisteret-api-ledigestillinger"
    - name: LEDIGE_STILLINGER_TARGET
      value: "prod-gcp:paw:paw-arbeidssoekerregisteret-api-ledigestillinger"
    - name: AB_TESTING_REGEX
      value: "[az]{100}" #Hentes fra SjekkABTestingGruppeTest, ingen skal matche i prod inntil videre
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 512Mi
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  kafka:
    pool: nav-prod
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  startup:
    failureThreshold: 10
    initialDelay: 12
    path: /internal/hasStarted
    periodSeconds: 10
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssoekerregisteret-for-personbruker
    outbound:
      rules:
        - application: paw-arbeidssoekerregisteret-api-ledigestillinger
      external:
        - host: pdl-api.prod-fss-pub.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-6144
        databases:
          - name: brukerprofiler

