package no.naw.paw.ledigestillinger.model

enum class Tag {
    DIREKTEMELDT_V1,
    HAR_KRAV_TIL_ARBEIDSERFARING_V1,
    INGEN_KRAV_TIL_ARBEIDSERFARING_V1,
    UKJENT_KRAV_TIL_ARBEIDSERFARING_V1,
    HAR_KRAV_TIL_UTDANNING_V1,
    INGEN_KRAV_TIL_UTDANNING_V1,
    UKJENT_KRAV_TIL_UTDANNING_V1,
    HAR_KRAV_TIL_FOERERKORT_V1,
    INGEN_KRAV_TIL_FOERERKORT_V1,
    UKJENT_KRAV_TIL_FOERERKORT_V1,
}