[kafkaTopology]
consumerVersion = "${KAFKA_PAW_EGENVURDERING_CONSUMER_VERSION}"
applicationIdPrefix = "egenvurdering-dialog-tjeneste"
egenvurderingTopic = "${KAFKA_PAW_EGENVURDERING_TOPIC}"

[veilarbdialogClientConfig]
url = "${DIALOG_TJENESTE_URL}"
target = "${DIALOG_TJENESTE_API_TARGET}"

[texasClientConfig]
endpoint = "${NAIS_TOKEN_ENDPOINT}"
