host = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_V2_ARBEIDSSOEKERREGISTERETAPIOPPSLAGV2_HOST}"
port = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_V2_ARBEIDSSOEKERREGISTERETAPIOPPSLAGV2_PORT}"
username = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_V2_ARBEIDSSOEKERREGISTERETAPIOPPSLAGV2_USERNAME}"
password = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_V2_ARBEIDSSOEKERREGISTERETAPIOPPSLAGV2_PASSWORD}"
database = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_V2_ARBEIDSSOEKERREGISTERETAPIOPPSLAGV2_DATABASE}"
jdbc= "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_V2_ARBEIDSSOEKERREGISTERETAPIOPPSLAGV2_JDBC_URL}"
