host = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_v2_ARBEIDSSOEKERREGISTERETAPIOPPSLAGV2_HOST}"
port = "${DATABASE_PORT}"
username = "${DATABASE_USERNAME}"
password = "${DATABASE_PASSWORD}"
database = "${DATABASE_DATABASE}"
