### GET Brukerprofil
GET {{baseUrl}}/api/v1/brukerprofil
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### PUT Tjenestestatus
PUT {{baseUrl}}/api/v1/brukerprofil/tjenestestatus/AKTIV
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### PUT Stillingssøk
PUT {{baseUrl}}/api/v1/brukerprofil/stillingssoek
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
    {
        "soekType": "STED_SOEK_V1",
        "fylker": [
            {
                "navn": "Oslo",
                "fylkesnummer": "03",
                "kommuner": []
            }
        ],
        "soekeord": [],
        "styrk08Kode": [
            "1330",
            "2166",
            "2514",
            "3514"
        ]
    }
]

### POST Stillinger
GET {{baseUrl}}/api/v1/ledigestillinger
Accept: application/json
Authorization: Bearer {{accessToken}}
