### POST /api/v4/snapshot by identitetsnummer med tokenx token
POST {{baseUrl}}/api/v4/snapshot
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("tokenx")}}

{
    "type": "IDENTITETSNUMMER",
    "identitetsnummer": "01017012345"
}

### POST /api/v4/snapshot by identitetsnummer med azure token
POST {{baseUrl}}/api/v4/snapshot
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "type": "IDENTITETSNUMMER",
    "identitetsnummer": "01017012345"
}




### POST /api/v4/perioder by identitetsnummer med tokenx token
POST {{baseUrl}}/api/v4/perioder
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("tokenx")}}

{
    "type": "IDENTITETSNUMMER",
    "identitetsnummer": "01017012345"
}

### POST /api/v4/perioder by identitetsnummer med azure token
POST {{baseUrl}}/api/v4/perioder?ordering=DESC
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "type": "IDENTITETSNUMMER",
    "identitetsnummer": "01017012345"
}

### POST /api/v4/perioder by perioder med tokenx token
POST {{baseUrl}}/api/v4/perioder
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("tokenx")}}

{
    "type": "PERIODER",
    "perioder": [
        "b42f2c7b-10b5-41a8-b415-f671457964e5"
    ]
}

### POST /api/v4/perioder by perioder med azure token
POST {{baseUrl}}/api/v4/perioder
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "type": "PERIODER",
    "perioder": [
        "b42f2c7b-10b5-41a8-b415-f671457964e5"
    ]
}
