### POST /api/v1/stillinger/{uuid}

POST {{devProxyBaseUrl}}/api/v1/proxy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{azure.accessToken}}

{
    "method": "POST",
    "url": "{{baseUrl}}/api/v3/snapshot",
    "body": {
        "type": "IDENTITETSNUMMER",
        "identitetsnummer": "52508219598"
    }
}

### POST Request /api/v3/tidslinjer by identitetsnummer med azure token

POST {{devProxyBaseUrl}}/api/v1/proxy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{azure.accessToken}}

{
    "method": "POST",
    "url": "{{baseUrl}}/api/v3/perioder",
    "body": {
        "type": "IDENTITETSNUMMER",
        "identitetsnummer": "11490887999"
    }
}
