### GET /api/docs/v1 med tokenx token
GET {{baseUrl}}/api/docs/v1/v1-spec.yaml
Accept: application/yaml

### GET /api/docs/v2 med tokenx token
GET {{baseUrl}}/api/docs/v2/v2-spec.yaml
Accept: application/yaml

### GET /api/docs/v3 med azure token
GET {{baseUrl}}/api/docs/v3/v3-spec.yaml
Accept: application/yaml