openapi: 3.0.3
info:
  title: Periode API
  description: API for handling arbeidssøkerperioder (job seeker periods)
  version: 1.0.0

paths:
  /api/v2/bekreftelser:
    post:
      description: "Hent alle bekreftelser for oppgitte perioder"
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          description: "https://www.w3.org/TR/trace-context/#traceparent-header-field-values"
          schema:
            type: "string"
            format: "traceparent"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                perioder:
                  type: array
                  items:
                    type: string
                    format: uuid
              required:
                - "perioder"
        required: true
      responses:
        "200":
          description: "OK"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: "object"


components:
  schemas:
    Periode:
      $ref: './meldinger/periode.yaml#/Periode'

    OpplysningerOmArbeidssoeker:
      $ref: './meldinger/opplysninger_om_arbeidssoeker.yaml#/OpplysningerOmArbeidssoeker'

    Profilering:
      $ref: './meldinger/profilering.yaml#/Profilering'

    Bekreftelse:
      $ref: './meldinger/bekreftelse.yaml#/Bekreftelse'

    PaaVegneAv:
      $ref: './meldinger/paa-vegne-av.yaml#/PaaVegneAv'

    #Responses
    BekreftelserResponse:
        type: object
        description: "Response for bekreftelser"
        properties:
            bekreftelser:
              type: array
              items:
                type: object
                properties:
                  gyldig:
                    type: boolean
                    description: "Angir om dette er en gyldig bekreftelse"
                  bekreftelse:
                    $ref: './meldinger/bekreftelse.yaml#/Bekreftelse'
        required:
            - bekreftelser
