apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-api-oppslag
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  ingresses:
    - https://oppslag-arbeidssoekerregisteret.intern.dev.nav.no
  port: 8080
  env:
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: PDL_TEMA
      value: "OPP"
    - name: KAFKA_TOPIC_PERIODER
      value: "paw.arbeidssokerperioder-v1"
    - name: KAFKA_TOPIC_OPPLYSNINGER
      value: "paw.opplysninger-om-arbeidssoeker-v1"
    - name: KAFKA_TOPIC_PROFILERING
      value: "paw.arbeidssoker-profilering-v1"
    - name: KAFKA_TOPIC_BEKREFTELSE
      value: "paw.arbeidssoker-bekreftelse-v1"
    - name: KAFKA_GROUP_ID_PERIODER
      value: "paw.arbeidssoekerregisteret-api-oppslag-v9"
    - name: KAFKA_GROUP_ID_OPPLYSNINGER
      value: "paw.arbeidssoekerregisteret-api-oppslag-v9"
    - name: KAFKA_GROUP_ID_PROFILERING
      value: "paw.arbeidssoekerregisteret-api-oppslag-v9"
    - name: KAFKA_GROUP_ID_BEKREFTELSE
      value: "paw.arbeidssoekerregisteret-api-oppslag-bekreftelse-v1"
    - name: DATABASE_HOST
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_HOST)"
    - name: DATABASE_PORT
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_PORT)"
    - name: DATABASE_USERNAME
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_USERNAME)"
    - name: DATABASE_PASSWORD
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_PASSWORD)"
    - name: DATABASE_DATABASE
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_DATABASE)"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering-for-veileder
        - application: arbeidssoekerregisteret-for-personbruker
        - application: paw-arbeidssoekerregisteret-api-dolly
        - application: tokenx-token-generator
          namespace: nais
        - application: azure-token-generator
          namespace: nais
        - application: saas-proxy
          namespace: teamcrm
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
        - application: arena
          namespace: teamarenanais
          cluster: dev-fss
        - application: aia-backend
          namespace: paw
          cluster: dev-gcp
        - application: paw-brukerstotte
          namespace: paw
          cluster: dev-gcp
        - application: dp-oppslag-arbeidssoker
          namespace: teamdagpenger
        - application: dp-dagpenger
          namespace: teamdagpenger
        - application: dp-soknadsdialog
          namespace: teamdagpenger
        - application: dp-saksbehandling-frontend
          namespace: teamdagpenger
        - application: dp-mine-dagpenger-frontend
          namespace: teamdagpenger
        - application: dp-rapportering
          namespace: teamdagpenger
        - application: dp-rapportering-personregister
          namespace: teamdagpenger
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: arbeidssokerregistrering
          namespace: paw
          cluster: dev-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: dev-fss
        - application: paw-brukerstotte
          namespace: paw
        - application: paw-arbeidssoekerregisteret-hendelselogg-backup
          namespace: paw
        - application: veilarbportefolje
          namespace: obo
          cluster: dev-gcp
        - application: veilarbperson
          namespace: obo
          cluster: dev-gcp
        - application: familie-ef-sak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: flex-arbeidssokerregister-oppdatering
          namespace: flex
        - application: sykepengesoknad-backend
          namespace: flex
        - application: isfrisktilarbeid
          namespace: teamsykefravr
    outbound:
      rules:
        - application: paw-tilgangskontroll
          namespace: paw
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-g1-small
        databases:
          - name: arbeidssoekerregisteretapioppslag
