openapi: "3.0.3"
info:
  title: "paw_arbeidssoekerregisteret_egenvurdering_api"
  description: "paw_arbeidssoekerregisteret_egenvurdering_api"
  version: "1.0.0"
paths:
  /api/v1/arbeidssoeker/profilering/egenvurdering:
    post:
      description: "Tar imot brukerens egenvurdering av profilering"
      security:
        - TokenXAuth: [ ]
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          description: "https://www.w3.org/TR/trace-context/#traceparent-header-field-values"
          schema:
            type: "string"
            format: "traceparent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EgenvurderingRequest"
        required: true
      responses:
        "202":
          description: "Accepted"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
        "400":
          description: "Bad Request"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "403":
          description: "Forbidden"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: "Internal Server Error"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "502":
          description: "Bad Gateway"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /api/v1/arbeidssoeker/profilering/egenvurdering/grunnlag:
    get:
      description: "Henter grunnlaget for en egenvurdering hvis det finnes"
      security:
        - TokenXAuth: [ ]
      responses:
        "200":
          description: "OK"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EgenvurderingGrunnlag"
        "400":
          description: "Bad Request"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "403":
          description: "Forbidden"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "404":
          description: "Not Found"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: "Internal Server Error"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "502":
          description: "Bad Gateway"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

components:
  securitySchemes:
    TokenXAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Oppslag som gjøres av arbeidssøker selv. Bruk et Bearer token fra TokenX.

        Eksempel: `Authorization: Bearer <token>`

        ```json
        { "acr": "Level4", "pid": "<fnr>" }
        ```
  schemas:
    EgenvurderingRequest:
      type: "object"
      properties:
        profileringId:
          type: "string"
          description: "Profilering id"
          format: uuid
        egenvurdering:
          $ref: "#/components/schemas/EgenvurdertTil"
      required:
        - "profileringId"
        - "egenvurdering"
    EgenvurdertTil:
      type: "string"
      enum:
        - "ANTATT_BEHOV_FOR_VEILEDNING"
        - "ANTATT_GODE_MULIGHETER"
        - "OPPGITT_HINDRINGER"
    EgenvurderingGrunnlag:
      type: object
      properties:
        grunnlag:
          $ref: "#/components/schemas/Profilering"
    Profilering:
      type: object
      properties:
        profileringId:
          type: "string"
          format: "uuid"
          description: "ID for profileringen"
        profilertTil:
          $ref: "#/components/schemas/ProfilertTil"
      required:
        - profileringId
        - profilertTil
    ProfilertTil:
      type: "string"
      enum:
        - "ANTATT_GODE_MULIGHETER"
        - "ANTATT_BEHOV_FOR_VEILEDNING"
        - "OPPGITT_HINDRINGER"
        - "UKJENT_VERDI"
        - "UDEFINERT"

    # --- Problem details med dependencies ---
    ProblemDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          format: uri
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - id
        - type
        - status
        - title
        - instance
        - timestamp
      example:
        id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
        type: "urn:paw:default:ukjent-feil"
        status: 500
        title: "Internal Server Error"
        detail: "Ukjent feil"
        instance: "/api/v3/bekreftelser"
        timestamp: "2021-01-01T12:00:00.000Z"
