openapi: "3.0.3"
info:
  title: "paw_arbeidssoekerregisteret_egenvurdering_api"
  description: "paw_arbeidssoekerregisteret_egenvurdering_api"
  version: "1.0.0"
paths:
  /internal/isAlive:
    get:
      description: "Service is alive probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/isReady:
    get:
      description: "Service is ready probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/metrics:
    get:
      description: "Prometheus metrics"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type:
          type: "string"
        title:
          type: "string"
        status:
          type: "number"
        detail:
          type: "string"
        instance:
          type: "string"
      required:
        - type
        - title
        - status
        - detail
        - instance
      example:
        type: "about:blank"
        title: "Forbidden"
        status: 403
        detail: "Access denied"
        instance: "/api/endpoint"
    HealthStatus:
      type: "string"
      enum:
        - "UNKNOWN"
        - "HEALTHY"
        - "UNHEALTHY"
