openapi: "3.0.3"
info:
  title: "paw_arbeidssoekerregisteret_egenvurdering_api"
  description: "paw_arbeidssoekerregisteret_egenvurdering_api"
  version: "1.0.0"
paths:
  /api/v1/arbeidssoeker/profilering/egenvurdering:
    post:
      description: "Tar imot brukerens egenvurdering av profilering"
      security:
        - TokenXAuth: []
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          description: "https://www.w3.org/TR/trace-context/#traceparent-header-field-values"
          schema:
            type: "string"
            format: "traceparent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EgenvurderingRequest"
        required: true
      responses:
        "202":
          description: "Accepted"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: "object"
        "400":
          description: "Bad Request"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "403":
          description: "Forbidden"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: "Internal Server Error"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /api/v1/arbeidssoeker/profilering/egenvurdering/grunnlag:
    get:
      description: "Henter grunnlaget for en egenvurdering hvis det finnes"
      security:
        - TokenXAuth: []
      responses:
        "200":
          description: "OK"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EgenvurderingGrunnlag"
        "400":
          description: "Bad Request"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "403":
          description: "Forbidden"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "404":
          description: "Not Found"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: "Internal Server Error"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

  /internal/isAlive:
    get:
      description: "Service is alive probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/isReady:
    get:
      description: "Service is ready probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/metrics:
    get:
      description: "Prometheus metrics"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
components:
  securitySchemes:
    TokenXAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Oppslag som gjøres av arbeidssøker selv. Bruk et Bearer token fra TokenX.

        Eksempel: `Authorization: Bearer <token>`

        ```json
        { "acr": "Level4", "pid": "<fnr>" }
        ```
  schemas:
    EgenvurderingRequest:
      type: "object"
      properties:
        profileringId:
          type: "string"
          description: "Profilering id"
          format: uuid
        egenvurdering:
          $ref: "#/components/schemas/Egenvurdering"
      required:
        - "profileringId"
        - "egenvurdering"
    Egenvurdering:
      type: "string"
      enum:
        - "ANTATT_BEHOV_FOR_VEILEDNING"
        - "ANTATT_GODE_MULIGHETER"
        - "OPPGITT_HINDRINGER"
    EgenvurderingGrunnlag:
      type: object
      properties:
        grunnlag:
            $ref: "#/components/schemas/Profilering"
    Profilering:
        type: object
        properties:
          profileringId:
            type: "string"
            format: "uuid"
            description: "ID for profileringen"
          profilertTil:
            $ref: "#/components/schemas/ProfilertTil"
        required:
            - profileringId
            - profilertTil
    ProfilertTil:
      type: "string"
      enum:
        - "ANTATT_GODE_MULIGHETER"
        - "ANTATT_BEHOV_FOR_VEILEDNING"
        - "OPPGITT_HINDRINGER"
    ProblemDetails:
      type: object
      properties:
        type:
          type: "string"
        title:
          type: "string"
        status:
          type: "number"
        detail:
          type: "string"
        instance:
          type: "string"
      required:
        - type
        - title
        - status
        - detail
        - instance
      example:
        type: "about:blank"
        title: "Forbidden"
        status: 403
        detail: "Access denied"
        instance: "/api/endpoint"
    HealthStatus:
      type: "string"
      enum:
        - "UNKNOWN"
        - "HEALTHY"
        - "UNHEALTHY"
