openapi: 3.0.3
info:
  version: v1
  title: Ledigestillinger API
  description: API for å hente stillinger
paths:
  "/api/v1/stillinger":
    post:
      tags:
        - Stillinger
      description: Finn stillinger
      operationId: finnStillinger
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinnStillingRequest"
        required: true
      responses:
        '200':
          description: Liste med stillinger
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Stilling"
        '304':
          description: Feed page is empty, or its contents have not changed since
            last time
        '400':
          description: Invalid input in the request
        '404':
          description: Could not find page
      deprecated: false
      security:
        - BearerAuth: [ ]
  "/api/v1/stillinger/{uuid}":
    get:
      tags:
        - Stillinger
      description: Hent stilling
      operationId: getStilling
      parameters:
        - name: uuid
          in: path
          description: Unit UUID for stillingen
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
      responses:
        '200':
          description: Stilling
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Stilling"
        '304':
          description: Feed page is empty, or its contents have not changed since
            last time
        '400':
          description: Invalid input in the request
        '404':
          description: Could not find page
      deprecated: false
      security:
        - BearerAuth: [ ]
components:
  schemas:
    FinnStillingRequest:
      type: object
      additionalProperties: false
      properties:
        uuid:
          type: string
          format: uuid
      required:
        - uuid
    Stilling:
      type: object
      additionalProperties: false
      properties:
        uuid:
          type: string
          format: uuid
        adnr:
          type: string
        tittel:
          type: string
        status:
          $ref: '#/components/schemas/StillingStatus'
        arbeidsgiverNavn:
          type: string
        publisertTimestamp:
          type: "string"
          format: "date-time"
          example: "2021-09-29T11:20:33.444Z"
        utloeperTimestamp:
          type: "string"
          format: "date-time"
          example: "2021-09-29T11:20:33.444Z"
      required:
        - uuid
        - tittel
        - status
        - publisertTimestamp
    StillingStatus:
      type: "string"
      enum:
        - "ACTIVE"
        - "INACTIVE"
        - "STOPPED"
        - "DELETED"
        - "REJECTED"
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
security: [ ]
