openapi: 3.0.3
info:
  version: v1
  title: Ledigestillinger API
  description: API for å hente stillinger
paths:
  "/api/v1/stillinger":
    post:
      tags:
        - Stillinger
      description: Finn stillinger
      operationId: finnStillinger
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinnStillingerRequest"
        required: true
      responses:
        '200':
          description: Inneholder liste med stillinger
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinnStillingerResponse"
        '304':
          description: Feed page is empty, or its contents have not changed since
            last time
        '400':
          description: Invalid input in the request
        '404':
          description: Could not find page
      deprecated: false
      security:
        - BearerAuth: [ ]
  "/api/v1/stillinger/{uuid}":
    get:
      tags:
        - Stillinger
      description: Hent stilling
      operationId: getStilling
      parameters:
        - name: uuid
          in: path
          description: Unit UUID for stillingen
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
      responses:
        '200':
          description: Stilling
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Stilling"
        '304':
          description: Feed page is empty, or its contents have not changed since
            last time
        '400':
          description: Invalid input in the request
        '404':
          description: Could not find page
      deprecated: false
      security:
        - BearerAuth: [ ]
components:
  schemas:
    FinnStillingerRequest:
      type: object
      additionalProperties: false
      properties:
        soekeord:
          type: array
          items:
            type: string
        kategorier:
          type: array
          items:
            type: string
        fylker:
          type: array
          items:
            "$ref": "#/components/schemas/Fylke"
        paging:
          "$ref": "#/components/schemas/Paging"
      required:
        - soekeord
        - kategorier
        - fylker
        - paging
    FinnStillingerResponse:
      type: object
      additionalProperties: false
      properties:
        stillinger:
          type: array
          items:
            $ref: '#/components/schemas/Stilling'
      required:
        - stillinger
    Stilling:
      type: object
      additionalProperties: false
      properties:
        uuid:
          type: string
          format: uuid
        adnr:
          type: string
        tittel:
          type: string
        status:
          $ref: '#/components/schemas/StillingStatus'
        jobbtittel:
          type: string
        ansettelsesform:
          type: string
        ansettelsesprosent:
          type: string
        stillingsantall:
          type: string
        arbeidsgiver:
          type: string
        kategorier:
          type: array
          items:
            "$ref": "#/components/schemas/Kategori"
        lokasjoner:
          type: array
          items:
            "$ref": "#/components/schemas/Lokasjon"
        soeknadsfrist:
          type: string
        publisert:
          type: string
          format: "date-time"
          example: "2021-09-29T11:20:33.444Z"
        utloeper:
          type: string
          format: "date-time"
          example: "2021-09-29T11:20:33.444Z"
      required:
        - uuid
        - tittel
        - status
        - publisert
        - kategorier
        - lokasjoner
    StillingStatus:
      type: string
      enum:
        - AKTIV
        - INAKTIV
        - STOPPET
        - SLETTET
        - AVVIST
    Kategori:
      type: object
      properties:
        kode:
          type: string
        normalisertKode:
          type: string
        navn:
          type: string
      required:
        - kode
        - normalisertKode
        - navn
    Fylke:
      type: object
      properties:
        fylkesnummer:
          type: string
        kommuner:
          type: array
          items:
            $ref: "#/components/schemas/Kommune"
      required:
        - kommuner
    Kommune:
      type: object
      properties:
        kommunenummer:
          type: string
      required:
        - kommunenummer
    Lokasjon:
      type: object
      properties:
        postkode:
          type: string
        poststed:
          type: string
        kommune:
          type: string
        kommunenummer:
          type: string
        fylke:
          type: string
        fylkesnummer:
          type: string
        land:
          type: string
      required:
        - land
    Soeknadsfrist:
      type: object
      properties:
        raw:
          type: string
          description: "Tekst fra datasettet for egenskapen søknadsfrist"
          example: "Her kan det stå hva som helst dersom fristType er Ukjent"
        fristType:
          type: string
          description: "Hvilken type frist er det"
          enum:
            - UKJENT
            - SNAREST
            - DATO
        dato:
          type: string
          format: date
          example: "2025-11-25"
          description: "Søknadsfrist, bare med dersom 'fristType' er DATO"
    Paging:
      type: object
      properties:
        page:
          type: integer
          default: 1
          example: 1
        pageSize:
          type: integer
          default: 10
          example: 10
        sortOrder:
          $ref: "#/components/schemas/SortOrder"
      required:
        - page
        - pageSize
        - sortOrder
    SortOrder:
      type: string
      enum:
        - ASC
        - DESC
      default: ASC
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
security: [ ]
