openapi: 3.0.3
info:
  version: v1
  title: Ledigestillinger API
  description: API for å hente stillinger
paths:
  "/api/v1/stillinger":
    post:
      tags:
        - Stillinger
      description: Finn stillinger
      operationId: finnStillinger
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinnStillingerRequest"
        required: true
      responses:
        '200':
          description: Inneholder liste med stillinger
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinnStillingerResponse"
        '304':
          description: Feed page is empty, or its contents have not changed since
            last time
        '400':
          description: Invalid input in the request
        '404':
          description: Could not find page
      deprecated: false
      security:
        - BearerAuth: [ ]
  "/api/v1/stillinger/{uuid}":
    get:
      tags:
        - Stillinger
      description: Hent stilling
      operationId: getStilling
      parameters:
        - name: uuid
          in: path
          description: Unit UUID for stillingen
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
      responses:
        '200':
          description: Stilling
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Stilling"
        '304':
          description: Feed page is empty, or its contents have not changed since
            last time
        '400':
          description: Invalid input in the request
        '404':
          description: Could not find page
      deprecated: false
      security:
        - BearerAuth: [ ]
components:
  schemas:
    FinnStillingerRequest:
      type: object
      additionalProperties: false
      properties:
        soekeord:
          type: array
          items:
            type: string
        kategorier:
          type: array
          items:
            "$ref": "#/components/schemas/Kategori"
        fylker:
          type: array
          items:
            "$ref": "#/components/schemas/Fylke"
        page:
          type: integer
          format: int32
          default: 1
          example: 1
        pageSize:
          type: integer
          format: int32
          default: 10
          example: 10
      required:
        - kategorier
        - fylker
        - page
        - pageSize
    FinnStillingerResponse:
      type: object
      additionalProperties: false
      properties:
        stillinger:
          type: array
          items:
            $ref: '#/components/schemas/Stilling'
    Stilling:
      type: object
      additionalProperties: false
      properties:
        uuid:
          type: string
          format: uuid
        adnr:
          type: string
        tittel:
          type: string
        status:
          $ref: '#/components/schemas/StillingStatus'
        jobbtittel:
          type: string
        ansettelsesform:
          type: string
        ansettelsesprosent:
          type: string
        stillingsantall:
          type: string
        arbeidsgiver:
          type: string
        soeknadsfrist:
          type: string
        publisert:
          type: "string"
          format: "date-time"
          example: "2021-09-29T11:20:33.444Z"
        utloeper:
          type: "string"
          format: "date-time"
          example: "2021-09-29T11:20:33.444Z"
      required:
        - uuid
        - tittel
        - status
        - publisert
    StillingStatus:
      type: "string"
      enum:
        - "AKTIV"
        - "INAKTIV"
        - "STOPPET"
        - "SLETTET"
        - "AVVIST"
    Kategori:
      type: "object"
      properties:
        kode:
          type: "string"
          example: "0101"
      required:
        - "kode"
    Fylke:
      type: "object"
      properties:
        fylkesnummer:
          type: "string"
          example: "91"
        kommuner:
          type: "array"
          items:
            $ref: "#/components/schemas/Kommune"
      required:
        - "kommuner"
    Kommune:
      type: "object"
      properties:
        kommunenummer:
          type: "string"
          example: "9107"
      required:
        - "kommunenummer"
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
security: [ ]
