openapi: 3.0.3
info:
  version: v1
  title: Ledigestillinger API
  description: API for å hente stillinger
paths:
  "/api/v1/stillinger":
    post:
      tags:
        - Stillinger
      description: Finn stillinger
      operationId: finnStillinger
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinnStillingerRequest"
        required: true
      responses:
        "200":
          description: Inneholder liste med stillinger
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinnStillingerResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "eea6958a-273d-4dbc-9c85-faaa37530cbf"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v1/stillinger"
                timestamp: "2021-01-01T12:00:00.000Z"
      deprecated: false
      security:
        - BearerAuth: [ ]
  "/api/v1/stillinger/{uuid}":
    get:
      tags:
        - Stillinger
      description: Hent stilling
      operationId: getStilling
      parameters:
        - name: uuid
          in: path
          description: Unit UUID for stillingen
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Stilling
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stilling"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "eea6958a-273d-4dbc-9c85-faaa37530cbf"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v1/stillinger/5a431182-f342-417d-b552-aa574a1063c7"
                timestamp: "2021-01-01T12:00:00.000Z"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "86b35435-d70b-4bea-a1e4-77e6c288e255"
                type: "urn:paw:stillinger:ikke-funnet"
                status: 404
                title: "Not Found"
                detail: "Stilling ikke funnet"
                instance: "/api/v1/stillinger/74a3b46e-7e77-4c6b-90e9-e8d021e704a2"
                timestamp: "2021-01-01T12:00:00.000Z"
      deprecated: false
      security:
        - BearerAuth: [ ]
components:
  schemas:
    FinnStillingerRequest:
      type: object
      additionalProperties: false
      properties:
        soekeord:
          type: array
          items:
            type: string
        kategorier:
          type: array
          items:
            type: string
        fylker:
          type: array
          items:
            $ref: "#/components/schemas/Fylke"
        paging:
          $ref: "#/components/schemas/Paging"
      required:
        - soekeord
        - kategorier
        - fylker
        - paging
    FinnStillingerResponse:
      type: object
      additionalProperties: false
      properties:
        stillinger:
          type: array
          items:
            $ref: '#/components/schemas/Stilling'
        paging:
          $ref: "#/components/schemas/Paging"
      required:
        - stillinger
        - paging
    Stilling:
      type: object
      additionalProperties: false
      properties:
        uuid:
          type: string
          format: uuid
        adnr:
          type: string
        tittel:
          type: string
        status:
          $ref: '#/components/schemas/StillingStatus'
        arbeidsgivernavn:
          type: string
        arbeidsgiver:
          nullable: true
          oneOf:
            - type: 'null'
            - $ref: "#/components/schemas/Arbeidsgiver"
        stillingstittel:
          type: string
        ansettelsesform:
          type: string
        stillingsprosent:
          $ref: "#/components/schemas/Stillingsprosent"
        stillingsantall:
          type: integer
        sektor:
          $ref: "#/components/schemas/Sektor"
        soeknadsfrist:
          $ref: "#/components/schemas/Frist"
        oppstartsfrist:
          $ref: "#/components/schemas/Frist"
        kategorier:
          type: array
          items:
            $ref: "#/components/schemas/Kategori"
        lokasjoner:
          type: array
          items:
            $ref: "#/components/schemas/Lokasjon"
        publisert:
          type: string
          format: "date-time"
          example: "2021-09-29T11:20:33.444Z"
        utloeper:
          type: string
          format: "date-time"
          nullable: true
          example: "2021-09-29T11:20:33.444Z"
      required:
        - uuid
        - tittel
        - status
        - stillingsprosent
        - sektor
        - soeknadsfrist
        - oppstartsfrist
        - kategorier
        - lokasjoner
        - publisert
    StillingStatus:
      type: string
      enum:
        - AKTIV
        - INAKTIV
        - STOPPET
        - SLETTET
        - AVVIST
    VisningGrad:
      type: string
      enum:
        - UBEGRENSET
        - BEGRENSET_INTERNT
        - BEGRENSET_ARBEIDSGIVER
        - BEGRENSET_KILDE
    Arbeidsgiver:
      type: object
      properties:
        orgForm:
          type: string
        orgNr:
          type: string
        parentOrgNr:
          type: string
        navn:
          type: string
        offentligNavn:
          type: string
      required:
        - orgForm
        - navn
        - offentligNavn
    Kategori:
      type: object
      properties:
        kode:
          type: string
        normalisertKode:
          type: string
        navn:
          type: string
      required:
        - kode
        - normalisertKode
        - navn
    Klassifisering:
      type: object
      properties:
        type:
          type: string
        kode:
          type: string
        navn:
          type: string
      required:
        - type
        - kode
        - navn
    Fylke:
      type: object
      properties:
        fylkesnummer:
          type: string
        kommuner:
          type: array
          items:
            $ref: "#/components/schemas/Kommune"
      required:
        - kommuner
    Sektor:
      type: string
      enum:
        - OFFENTLIG
        - PRIVAT
        - UKJENT
    Kommune:
      type: object
      properties:
        kommunenummer:
          type: string
      required:
        - kommunenummer
    Lokasjon:
      type: object
      properties:
        postkode:
          type: string
        poststed:
          type: string
        kommune:
          type: string
        kommunenummer:
          type: string
        fylke:
          type: string
        fylkesnummer:
          type: string
        land:
          type: string
      required:
        - land
    Egenskap:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      required:
        - key
        - value
    Frist:
      type: object
      properties:
        verdi:
          type: string
          description: "Tekst fra datasettet for egenskapen"
          example: "Her kan det stå hva som helst dersom type er UKJENT"
        type:
          $ref: "#/components/schemas/FristType"
        dato:
          type: string
          format: date
          nullable: true
          example: "2025-11-25"
          description: "Frist, bare med dersom 'type' er DATO"
      required:
        - type
    FristType:
      type: string
      enum:
        - DATO
        - SNAREST
        - FORTLOEPENDE
        - UKJENT
    Stillingsprosent:
      type: string
      enum:
        - HELTID
        - DELTID
        - UKJENT
    Paging:
      type: object
      properties:
        page:
          type: integer
          default: 1
          example: 1
        pageSize:
          type: integer
          default: 10
          example: 10
        sortOrder:
          $ref: "#/components/schemas/SortOrder"
      required:
        - page
        - pageSize
        - sortOrder
    SortOrder:
      type: string
      enum:
        - ASC
        - DESC
      default: ASC
    ProblemDetails:
      type: object
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          type: "string"
          format: "uri"
        status:
          type: "integer"
        title:
          type: "string"
        detail:
          type: "string"
        instance:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
      required:
        - id
        - type
        - status
        - title
        - detail
        - instance
        - timestamp
      example:
        id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
        type: "urn:paw:default:ukjent-feil"
        status: 500
        title: "Internal Server Error"
        detail: "Ukjent feil"
        instance: "/api/v1/stillinger"
        timestamp: "2021-01-01T12:00:00.000Z"
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
security: [ ]
