[kafkaTopology]
consumerVersion = "paw-egenvurdering-dialog-tjeneste-consumer-v1"
applicationIdPrefix = "egenvurdering-dialog-tjeneste"
egenvurderingTopic = "arbeidssoker-egenvurdering-beta-v2"

[veilarbdialogClientConfig]
url = "MOCK"
scope = "api://<cluster>.<namespace>.<outbound-app-name>/.default"