### POST Request
POST {{baseUrl}}/api/v1/stillinger
Content-Type: application/json
Authorization: Bearer {{$auth.token("tokenx")}}

{
    "soekeord": [],
    "kategorier": [
        "9999"
    ],
    "fylker": [
        {
            "fylkesnummer": "55",
            "kommuner": []
        }
    ],
    "paging": {
        "page": 1,
        "pageSize": 10,
        "sortOrder": "ASC"
    }
}

###