openapi: "3.0.3"
info:
  title: "BrukerprofilerI"
  description: "Noe greier"
  version: "0.1.0"
servers:
  - url: "https://brukerprofiler-arbeidssoekerregisteret.intern.dev.nav.no"
    description: "Development"
paths:
  /api/v1/brukerprofil/erTjenestenLedigeStillingerAktiv/{aktiv} :
    put:
      description: "Sett om tjenesten ledige stillinger er aktiv for en gitt bruker"
      parameters:
        - name: "aktiv"
          in: "path"
          required: true
          schema:
            type: "boolean"
      responses:
        "204":
          description: "No Content"
        "404":
          description: "Not Found"
  /api/v1/brukerprofil/erIkkeInteressert/{erIkkeInteressert} :
    put:
      description: "Sett om en bruker er ikke interessert i ledige stillinger"
      parameters:
        - name: "erIkkeInteressert"
          in: "path"
          required: true
          schema:
            type: "boolean"
      responses:
        "204":
          description: "No Content"
        "404":
          description: "Not Found"
  /api/v1/brukerprofil/ :
    get:
      description: "Hent brukerprofil for en gitt bruker"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Brukerprofil"
  /api/v1/kodeverk/fylker :
    get:
      description: "Hent alle fylker og deres kommuner"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Fylke"
components:
  schemas:
    Brukerprofil:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
          example: "12345678901"
          format: "identitetsnummer"
        kanTilbysTjenestenLedigeStillinger:
          type: "boolean"
          example: true
        erTjenestenLedigeStillingerAktiv:
          type: "boolean"
          example: true
        stillingssoek:
          type: "array"
          items:
            $ref: "#/components/schemas/Stillingssoek"
        erIkkeInteressert:
          type: "boolean"
          example: false
      required:
        - "identitetsnummer"
        - "kanTilbysTjenestenLedigeStillinger"
        - "erTjenestenLedigeStillingerAktiv"
        - "erIkkeInteressert"
    Stillingssoek:
      oneOf:
        - $ref: "#/components/schemas/StedSoek"
        - $ref: "#/components/schemas/ReiseveiSoek"
      discriminator:
        propertyName: soekType
        mapping:
          STED_SOEK_V1: '#/components/schemas/StedSoek'
          REISEVEI_SOEK_V1: '#/components/schemas/ReiseveiSoek'
    StedSoek:
      type: "object"
      properties:
        soekType:
          type: "string"
          enum:
            - "STED_SOEK_V1"
        fylker:
          type: "array"
          items:
            $ref: "#/components/schemas/Fylke"
        soekeord:
          type: "array"
          items:
            type: "string"
            example: "Tryllekunstner"
      required:
        - "soekType"
        - "fylker"
        - "soekeord"

    Fylke:
      type: "object"
      properties:
        navn:
          type: "string"
          example: "Buskerud"
        kommuner:
          type: "array"
          items:
            type: "string"
            example: "Nedre Eiker"
      required:
        - "navn"
        - "kommuner"

    ReiseveiSoek:
      type: "object"
      properties:
        soekType:
          type: "string"
          enum:
            - "REISEVEI_SOEK_V1"
        maksAvstandKm:
          type: "integer"
          example: 42
        postnummer:
          type: "string"
          example: "5145"
          format: "postnummer"
        soekeord:
          type: "array"
          items:
            type: "string"
            example: "Tryllekunstner"
      required:
        - "soekType"
        - "maksAvstandKm"
        - "postnummer"
        - "soekeord"
