openapi: "3.0.3"
info:
  title: "BrukerprofilerI"
  description: "Noe greier"
  version: "0.1.0"
servers:
  - url: "https://brukerprofiler-arbeidssoekerregisteret.intern.dev.nav.no"
    description: "Development"
paths:
  /api/v1/brukerprofil/ :
    get:
      description: "Hent brukerprofil for en gitt bruker"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Brukerprofil"
components:
  schemas:
    Brukerprofil:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
          example: "12345678901"
          format: "identitetsnummer"
        kanTilbysTjenestenLedigeStillinger:
          type: "boolean"
          example: true
        erTjenestenLedigeStillingerAktiv:
          type: "boolean"
          example: true
        stillingssoek:
          type: "array"
          items:
            $ref: "#/components/schemas/Stillingssoek"
        erIkkeInteressert:
          type: "boolean"
          example: false
      required:
        - "identitetsnummer"
        - "kanTilbysTjenestenLedigeStillinger"
        - "erTjenestenLedigeStillingerAktiv"
        - "erIkkeInteressert"
    Stillingssoek:
      oneOf:
        - $ref: "#/components/schemas/StedSoek"
        - $ref: "#/components/schemas/AvansertSoek"
      discriminator:
        propertyName: soekType
        mapping:
          STED_SOEK_V1: '#/components/schemas/StedSoek'
          AVANSERT_SOEK_V1: '#/components/schemas/AvansertSoek'
    StedSoek:
      type: "object"
      properties:
        soekType:
          type: "string"
          enum:
            - "STED_SOEK_V1"
        fylker:
          type: "array"
          items:
            $ref: "#/components/schemas/Fylke"
        soekeord:
          type: "array"
          items:
            type: "string"
            example: "Tryllekunstner"
      required:
        - "soekType"
        - "fylker"
        - "soekeord"

    Fylke:
      type: "object"
      properties:
        navn:
          type: "string"
          example: "Buskerud"
        kommuner:
          type: "array"
          items:
            type: "string"
            example: "Nedre Eiker"
      required:
        - "navn"
        - "kommuner"

    AvansertSoek:
      type: "object"
      properties:
        soekType:
          type: "string"
          enum:
            - "AVANSERT_SOEK_V1"
        hugga:
          type: "integer"
          example: 42
        styrk08:
          type: "string"
          example: "1234"
          format: "styrk08"
      required:
        - "soekType"
        - "hugga"
        - "styrk08"
