openapi: "3.0.3"
info:
  title: "Brukerprofiler"
  description: "API for å stillingssøk i Arbeidssøkerregisteret"
  version: "0.1.0"
servers:
  - url: "https://brukerpofiler-arbeidssoekerregisteret.intern.dev.nav.no"
    description: "Development"
paths:
  /api/v1/brukerprofil/erTjenestenLedigeStillingerAktiv/{aktiv} :
    put:
      description: "Sett om tjenesten ledige stillinger er aktiv for en gitt bruker"
      parameters:
        - name: "aktiv"
          in: "path"
          required: true
          schema:
            type: "boolean"
      responses:
        "204":
          description: "No Content"
        "404":
          description: "Not Found"
        "403":
          description: "Forbidden - brukeren kan ikke tilbys tjenesten ledige stillinger"
  /api/v1/brukerprofil/erIkkeInteressert/{erIkkeInteressert} :
    put:
      description: "Sett om en bruker er ikke interessert i ledige stillinger"
      parameters:
        - name: "erIkkeInteressert"
          in: "path"
          required: true
          schema:
            type: "boolean"
      responses:
        "204":
          description: "No Content"
        "404":
          description: "Not Found"
  /api/v1/brukerprofil/ :
    get:
      description: "Hent brukerprofil for en gitt bruker"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Brukerprofil"
  /api/v1/ledigestillinger :
    get:
      description: "Hent brukerprofil for en gitt bruker"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LedigeStillinger"
        "404":
          description: "Bruker har ikke tjenesten aktiv eller har ingen søk konfigurert"

  /api/v1/kodeverk/fylker :
    get:
      description: "Hent alle fylker og deres kommuner"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Fylke"
  /api/v1/kodeverk/styrk08 :
    get:
      description: "Hent hele STYRK-08 treet"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/StyrkTreNode"

components:
  schemas:
    Brukerprofil:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
          example: "12345678901"
          format: "identitetsnummer"
        kanTilbysTjenestenLedigeStillinger:
          type: "boolean"
          example: true
        erTjenestenLedigeStillingerAktiv:
          type: "boolean"
          example: true
        stillingssoek:
          type: "array"
          items:
            $ref: "#/components/schemas/Stillingssoek"
        erIkkeInteressert:
          type: "boolean"
          example: false
      required:
        - "identitetsnummer"
        - "kanTilbysTjenestenLedigeStillinger"
        - "erTjenestenLedigeStillingerAktiv"
        - "erIkkeInteressert"
    Stillingssoek:
      oneOf:
        - $ref: "#/components/schemas/StedSoek"
        - $ref: "#/components/schemas/ReiseveiSoek"
      discriminator:
        propertyName: soekType
        mapping:
          STED_SOEK_V1: '#/components/schemas/StedSoek'
          REISEVEI_SOEK_V1: '#/components/schemas/ReiseveiSoek'
    StedSoek:
      type: "object"
      properties:
        soekType:
          type: "string"
          enum:
            - "STED_SOEK_V1"
        fylker:
          type: "array"
          items:
            $ref: "#/components/schemas/Fylke"
        soekeord:
          type: "array"
          items:
            type: "string"
            example: "Tryllekunstner"
        styrk08:
          type: "array"
          items:
            type: "string"
            format: "styrk08"
            example: "124"
      required:
        - "soekType"
        - "fylker"
        - "soekeord"

    Fylke:
      type: "object"
      properties:
        navn:
          type: "string"
          example: "Buskerud"
        kommuner:
          type: "array"
          items:
            $ref: "#/components/schemas/Kommune"
        fylkesnummer:
          type: "string"
          example: "46"
          format: "fylkesnummer"
      required:
        - "navn"
        - "kommuner"
    Kommune:
      type: "object"
      properties:
        navn:
          type: "string"
          example: "Bergen"
        kommunenummer:
          type: "string"
          example: "4601"
          format: "kommunenummer"
      required:
        - "navn"
        - "kommunenummer"
    Styrk:
      type: "object"
      properties:
        level:
          type: "string"
          example: "1"
          description: Level 1-4
        code:
          type: "string"
          example: "1234"
          format: "styrk08"
        name:
          type: "string"
          example: "Jordbrukere"
      required:
        - "level"
        - "code"
        - "name"
    StyrkTreNode:
      type: "object"
      properties:
        styrk:
          $ref: "#/components/schemas/Styrk"
        children:
          type: "array"
          description: Tom dersom dette er et blad i treet (styrk kode på nivå 4).
          items:
            $ref: "#/components/schemas/StyrkTreNode"
      required:
        - "styrk"
        - "children"
    ReiseveiSoek:
      type: "object"
      description: "Denne søketypen er ikke støttet ennå, og blir kanskje aldri støttet."
      properties:
        soekType:
          type: "string"
          enum:
            - "REISEVEI_SOEK_V1"
        maksAvstandKm:
          type: "integer"
          example: 42
        postnummer:
          type: "string"
          example: "5145"
          format: "postnummer"
        soekeord:
          type: "array"
          items:
            type: "string"
            example: "Tryllekunstner"
      required:
        - "soekType"
        - "maksAvstandKm"
        - "postnummer"
        - "soekeord"
    LedigeStillinger:
      type: "object"
      properties:
        sistKjoert:
          type: "string"
          format: "date-time"
          example: "2025-10-20T12:00:00Z"
        soek:
          $ref: "#/components/schemas/Stillingssoek"
        resultat:
          type: "array"
          items:
            $ref: "#/components/schemas/Stilling"
      required:
        - "soek"
        - "stillinger"
        - "resultat"
    Stilling:
      type: "object"
      properties:
        tittel:
          type: "string"
          example: "Utvikler"
        stillingbeskrivelse:
          type: "string"
          example: "Backendutikler/Java"
        publisert:
          type: "string"
          format: "date-time"
          example: "2025-10-17T10:30:00Z"
        soeknadsfrist:
          type: "string"
          format: "date-time"
          example: "2025-11-17T23:59:59Z"
        land:
          type: "string"
          example: "Norge"
        kommune:
          type: "string"
          example: "Oslo"
      required:
        - "tittel"
        - "publisert"
        - "land"
