perioderTopic = "${KAFKA_TOPIC_PERIODER}"
opplysningerTopic = "${KAFKA_TOPIC_OPPLYSNINGER}"
profileringTopic = "${KAFKA_TOPIC_PROFILERING}"
bekreftelseTopic = "${KAFKA_TOPIC_BEKREFTELSE}"
perioderGroupId = "${KAFKA_GROUP_ID_PERIODER}"
opplysningerGroupId = "${KAFKA_GROUP_ID_OPPLYSNINGER}"
profileringGroupId = "${KAFKA_GROUP_ID_PROFILERING}"
bekreftelseGroupId = "${KAFKA_GROUP_ID_BEKREFTELSE}"
