apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-microfrontend-toggler
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  env:
    - name: KAFKA_TOGGLE_PRODUCER_ID_SUFFIX
      value: "toggle-producer-v1"
    - name: KAFKA_ARBEIDSSOKERPERIODER_STREAM_ID_SUFFIX
      value: "arbeidssokerperioder-stream-v1"
    - name: KAFKA_SISTE_14A_VEDTAK_STREAM_ID_SUFFIX
      value: "siste-14a-vedtak-stream-v1"
    - name: KAFKA_PAW_ARBEIDSSOKERPERIODER_TOPIC
      value: "paw.arbeidssokerperioder-v1"
    - name: KAFKA_PAW_BERIKET_14A_VEDTAK_TOPIC
      value: "paw.beriket-14a-vedtak-v1"
    - name: KAFKA_PTO_SISTE_14A_VEDTAK_TOPIC
      value: "pto.siste-14a-vedtak-v1"
    - name: KAFKA_TMS_MICROFRONTEND_TOPIC
      value: "min-side.aapen-microfrontend-v1"
    - name: KAFKA_KEYS_SCOPE
      value: "api://prod-gcp.paw.paw-kafka-key-generator/.default"
    - name: DEPREKERING_BEHOVSVURDERING_AKTIVERT
      value: "true"
    - name: DEPREKERING_BEHOVSVURDERING_TIDSPUNKT
      value: "2025-12-11T07:00:00+01:00"
    - name: DEPREKERING_BEHOVSVURDERING_CSV_FIL
      value: "/var/run/secrets/paw-microfrontend-toggler-csv/data.csv"
    - name: DEPREKERING_BEHOVSVURDERING_PUNCTUATOR_SCHEDULE
      value: "PT15M"
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 40m
      memory: 1024Mi
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
    streams: true
  filesFrom:
    - secret: paw-microfrontend-toggler-csv
      mountPath: /var/run/secrets/paw-microfrontend-toggler-csv
  accessPolicy:
    inbound:
      rules:
        - application: aia-backend
    outbound:
      rules:
        - application: paw-kafka-key-generator
          namespace: paw
